pipeline:
  - name: load_data
    class: src.components.loader.DataLoader
    method: load_from_pdf
    params:
      metadata: {}
    input:
      pdf_path: "data/pdfs/wp_generative_ai_risk_management_in_fs.pdf"
      split_from_mid: True
    output: docs

  - name: chunking
    class: src.components.chunker.TextSplitter
    method: split
    params:
      chunk_size: 1000
      chunk_overlap: 100
    input:
      docs: docs
    output: split_docs

  - name: embedding
    class: src.components.embedder.DocEmbedder
    method: embed
    params:
      model_name: "all-MiniLM-L6-v2"
      vs_name: "faiss_index_google_genai_risk_mgmt"
    input:
      split_docs: split_docs
      persist_vs: "serverless"
      tablename: "faiss_index_google_genai_risk_mgmt"
    output: vectorstore

